// Dead by Daylight perk list (name, icon, owner character) generated from the backend's
// survivorperks.json / killerperks.json. The backend has no list endpoint, only /perksS/:name and /perksK/:name.
const ICON_BASE = "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/";

const toPerk = role => ([name, icon, owner]) => ({ name, image: icon.startsWith('https://') ? icon : ICON_BASE + icon, owner, role });

const SURVIVOR = [
    ["Ace in the Hole", "2/24/IconPerks_aceInTheHole.png", "Ace Visconti"],
    ["Adrenaline", "f/f7/IconPerks_adrenaline.png", "Meg Thomas"],
    ["Aftercare", "0/0d/IconPerks_aftercare.png", "Jeff Johansen"],
    ["Alert", "7/71/IconPerks_alert.png", "Feng Min"],
    ["Any Means Necessary", "7/79/IconPerks_anyMeansNecessary.png", "Yui Kimura"],
    ["Appraisal", "c/c1/IconPerks_appraisal.png", "Élodie Rakoto"],
    ["Autodidact", "9/96/IconPerks_autodidact.png", "Adam Francis"],
    ["Balanced Landing", "5/5e/IconPerks_balancedLanding.png", "Nea Karlsson"],
    ["Better than New", "b/b1/IconPerks_betterThanNew.png", "Rebecca Chambers"],
    ["Bite the Bullet", "a/a5/IconPerks_biteTheBullet.png", "Leon Scott Kennedy"],
    ["Blast Mine", "1/1c/IconPerks_blastMine.png", "Jill Valentine"],
    ["Blood Pact", "c/c9/IconPerks_bloodPact.png", "Cheryl Mason"],
    ["Boil Over", "f/f5/IconPerks_boilOver.png", "Kate Denson"],
    ["Bond", "a/a0/IconPerks_bond.png", "Dwight Fairfield"],
    ["Boon: Circle of Healing", "5/54/IconPerks_boonCircleOfHealing.png", "Mikaela Reid"],
    ["Boon: Dark Theory", "6/60/IconPerks_boonDarkTheory.png", "Yoichi Asakawa"],
    ["Boon: Exponential", "7/76/IconPerks_boonExponential.png", "Jonah Vasquez"],
    ["Boon: Shadow Step", "c/c7/IconPerks_boonShadowStep.png", "Mikaela Reid"],
    ["Borrowed Time", "a/a3/IconPerks_borrowedTime.png", "William \"Bill\" Overbeck"],
    ["Botany Knowledge", "1/1e/IconPerks_botanyKnowledge.png", "Claudette Morel"],
    ["Breakdown", "6/6c/IconPerks_breakdown.png", "Jeff Johansen"],
    ["Breakout", "d/d0/IconPerks_breakout.png", "Yui Kimura"],
    ["Buckle Up", "7/74/IconPerks_buckleUp.png", "Ash J. Williams"],
    ["Built to Last", "3/3b/IconPerks_builtToLast.png", "Felix Richter"],
    ["Calm Spirit", "6/6c/IconPerks_calmSpirit.png", "Jake Park"],
    ["Clairvoyance", "9/91/IconPerks_clairvoyance.png", "Mikaela Reid"],
    ["Corrective Action", "4/4f/IconPerks_correctiveAction.png", "Jonah Vasquez"],
    ["Counterforce", "d/d1/IconPerks_counterforce.png", "Jill Valentine"],
    ["Dance With Me", "1/17/IconPerks_danceWithMe.png", "Kate Denson"],
    ["Dark Sense", "9/92/IconPerks_darkSense.png", ""],
    ["Dead Hard", "7/75/IconPerks_deadHard.png", "David King"],
    ["Deception", "e/eb/IconPerks_deception.png", "Élodie Rakoto"],
    ["Decisive Strike", "e/ee/IconPerks_decisiveStrike.png", "Laurie Strode"],
    ["Déjà Vu", "8/89/IconPerks_dejaVu.png", ""],
    ["Deliverance", "7/7e/IconPerks_deliverance.png", "Adam Francis"],
    ["Desperate Measures", "8/84/IconPerks_desperateMeasures.png", "Felix Richter"],
    ["Detective's Hunch", "7/7b/IconPerks_detectivesHunch.png", "David Tapp"],
    ["Distortion", "4/41/IconPerks_distortion.png", "Jeff Johansen"],
    ["Diversion", "a/a6/IconPerks_diversion.png", "Adam Francis"],
    ["Empathic Connection", "1/14/IconPerks_empathicConnection.png", "Yoichi Asakawa"],
    ["Empathy", "a/ae/IconPerks_empathy.png", "Claudette Morel"],
    ["Fast Track", "7/75/IconPerks_fastTrack.png", "Yun-Jin Lee"],
    ["Flashbang", "d/db/IconPerks_flashbang.png", "Leon Scott Kennedy"],
    ["Flip-Flop", "3/31/IconPerks_flip-Flop.png", "Ash J. Williams"],
    ["Fogwise", "9/90/IconPerks_fogwise.png", "Vittorio Toscano"],
    ["For the People", "3/31/IconPerks_forThePeople.png", "Zarina Kassir"],
    ["Guardian", "2/23/IconPerks_guardian.png", ""],
    ["Head On", "c/cb/IconPerks_headOn.png", "janeromero"],
    ["Hope", "1/18/IconPerks_hope.png", ""],
    ["Hyperfocus", "5/5d/IconPerks_hyperfocus.png", "Rebecca Chambers"],
    ["Inner Focus", "7/7e/IconPerks_innerFocus.png", "Haddie Kaur"],
    ["Inner Healing", "d/df/IconPerks_innerHealing.png", ""],
    ["Iron Will", "5/58/IconPerks_ironWill.png", "Jake Park"],
    ["Kindred", "a/a8/IconPerks_kindred.png", ""],
    ["Kinship", "1/1d/IconPerks_camaraderie.png", ""],
    ["Leader", "3/3d/IconPerks_leader.png", "Dwight Fairfield"],
    ["Left Behind", "c/c3/IconPerks_leftBehind.png", "William \"Bill\" Overbeck"],
    ["Lightweight", "6/67/IconPerks_lightweight.png", ""],
    ["Lithe", "c/cc/IconPerks_lithe.png", "Feng Min"],
    ["Low Profile", "f/fb/IconPerks_lowProfile.png", "Ada Wong"],
    ["Lucky Break", "a/a7/IconPerks_luckyBreak.png", "Yui Kimura"],
    ["Mettle of Man", "5/52/IconPerks_mettleOfMan.png", "Ash J. Williams"],
    ["No Mither", "f/f5/IconPerks_noMither.png", "David King"],
    ["No One Left Behind", "b/b0/IconPerks_noOneLeftBehind.png", ""],
    ["Object of Obsession", "2/2b/IconPerks_objectOfObsession.png", "Laurie Strode"],
    ["Off the Record", "9/9e/IconPerks_offTheRecord.png", "Zarina Kassir"],
    ["Open-Handed", "5/5d/IconPerks_open-Handed.png", "Ace Visconti"],
    ["Overcome", "8/82/IconPerks_overcome.png", "Jonah Vasquez"],
    ["Overzealous", "9/99/IconPerks_overzealous.png", "Haddie Kaur"],
    ["Parental Guidance", "4/46/IconPerks_parentalGuidance.png", "Yoichi Asakawa"],
    ["Pharmacy", "f/f1/IconPerks_pharmacy.png", "Quentin Smith"],
    ["Plunderer's Instinct", "2/28/IconPerks_plunderersInstinct.png", ""],
    ["Poised", "5/52/IconPerks_poised.png", "janeromero"],
    ["Potential Energy", "0/07/IconPerks_potentialEnergy.png", "Vittorio Toscano"],
    ["Power Struggle", "4/4b/IconPerks_powerStruggle.png", "Élodie Rakoto"],
    ["Premonition", "3/39/IconPerks_premonition.png", ""],
    ["Prove Thyself", "0/0f/IconPerks_proveThyself.png", "Dwight Fairfield"],
    ["Quick & Quiet", "1/14/IconPerks_quickAndQuiet.png", "Meg Thomas"],
    ["Quick Gambit", "f/f7/IconPerks_quickGambit.png", "Vittorio Toscano"],
    ["Reactive Healing", "5/5a/IconPerks_reactiveHealing.png", "Ada Wong"],
    ["Reassurance", "5/5b/IconPerks_reassurance.png", "Rebecca Chambers"],
    ["Red Herring", "1/1c/IconPerks_redHerring.png", "Zarina Kassir"],
    ["Renewal", "7/7b/IconPerks_renewal.png", ""],
    ["Repressed Alliance", "3/31/IconPerks_repressedAlliance.png", "Cheryl Mason"],
    ["Residual Manifest", "d/d0/IconPerks_residualManifest.png", "Haddie Kaur"],
    ["Resilience", "e/ee/IconPerks_resilience.png", ""],
    ["Resurgence", "f/f3/IconPerks_resurgence.png", "Jill Valentine"],
    ["Rookie Spirit", "2/2f/IconPerks_rookieSpirit.png", "Leon Scott Kennedy"],
    ["Saboteur", "0/0e/IconPerks_saboteur.png", "Jake Park"],
    ["Self-Aware", "7/7c/IconPerks_fixated.png", ""],
    ["Self-Care", "b/b2/IconPerks_self-Care.png", "Claudette Morel"],
    ["Self-Preservation", "4/43/IconPerks_self-Preservation.png", "Yun-Jin Lee"],
    ["Situational Awareness", "d/da/IconPerks_situationalAwareness.png", ""],
    ["Slippery Meat", "0/03/IconPerks_slipperyMeat.png", ""],
    ["Small Game", "d/dc/IconPerks_smallGame.png", ""],
    ["Smash Hit", "e/e0/IconPerks_smashHit.png", "Yun-Jin Lee"],
    ["Sole Survivor", "8/8e/IconPerks_soleSurvivor.png", "Laurie Strode"],
    ["Solidarity", "9/9e/IconPerks_solidarity.png", "janeromero"],
    ["Soul Guard", "a/a5/IconPerks_soulGuard.png", "Cheryl Mason"],
    ["Spine Chill", "5/57/IconPerks_spineChill.png", ""],
    ["Sprint Burst", "e/e4/IconPerks_sprintBurst.png", "Meg Thomas"],
    ["Stake Out", "c/cd/IconPerks_stakeOut.png", "David Tapp"],
    ["Streetwise", "f/ff/IconPerks_streetwise.png", "Nea Karlsson"],
    ["Technician", "6/62/IconPerks_technician.png", "Feng Min"],
    ["Tenacity", "9/9d/IconPerks_tenacity.png", "David Tapp"],
    ["This Is Not Happening", "5/58/IconPerks_thisIsNotHappening.png", ""],
    ["Unbreakable", "4/4a/IconPerks_unbreakable.png", "William \"Bill\" Overbeck"],
    ["Up the Ante", "a/a3/IconPerks_upTheAnte.png", "Ace Visconti"],
    ["Urban Evasion", "c/c7/IconPerks_urbanEvasion.png", "Nea Karlsson"],
    ["Vigil", "4/46/IconPerks_vigil.png", "Quentin Smith"],
    ["Visionary", "7/7c/IconPerks_visionary.png", "Felix Richter"],
    ["Wake Up!", "f/fd/IconPerks_wakeUp.png", "Quentin Smith"],
    ["We'll Make It", "8/8a/IconPerks_wellMakeIt.png", ""],
    ["We're Gonna Live Forever", "b/b8/IconPerks_wereGonnaLiveForever.png", "David King"],
    ["Windows of Opportunity", "1/17/IconPerks_windowsOfOpportunity.png", "Kate Denson"],
    ["Wiretap", "2/23/IconPerks_wiretap.png", "Ada Wong"],
];

const KILLER = [
    ["A Nurse's Calling", "f/fe/IconPerks_aNursesCalling.png", "The Nurse"],
    ["Agitation", "a/ac/IconPerks_agitation.png", "The Trapper"],
    ["Awakened Awareness", "9/97/IconPerks_awakenedAwareness.png", "The Mastermind"],
    ["Bamboozle", "7/7a/IconPerks_bamboozle.png", "The Clown"],
    ["Barbecue & Chilli", "5/51/IconPerks_barbecueAndChilli.png", "The Cannibal"],
    ["Beast of Prey", "7/77/IconPerks_beastOfPrey.png", "The Huntress"],
    ["Bitter Murmur", "5/5a/IconPerks_bitterMurmur.png", ""],
    ["Blood Echo", "c/c3/IconPerks_bloodEcho.png", "The Oni"],
    ["Blood Warden", "e/eb/IconPerks_bloodWarden.png", "The Nightmare"],
    ["Bloodhound", "e/e0/IconPerks_bloodhound.png", "The Wraith"],
    ["Brutal Strength", "3/3d/IconPerks_brutalStrength.png", "The Trapper"],
    ["Call of Brine", "3/3b/IconPerks_callOfBrine.png", "The Onryō"],
    ["Claustrophobia", "c/c6/IconPerks_cruelLimits.png", ""],
    ["Corrupt Intervention", "1/10/IconPerks_corruptIntervention.png", "The Plague"],
    ["Coulrophobia", "4/45/IconPerks_coulrophobia.png", "The Clown"],
    ["Coup de Grâce", "b/bd/IconPerks_coupDeGr%C3%A2ce.png", "The Twins"],
    ["Dark Devotion", "4/4f/IconPerks_darkDevotion.png", "The Plague"],
    ["Darkness Revealed", "e/ed/IconPerks_darknessRevealed.png", "The Dredge"],
    ["Dead Man's Switch", "c/c3/IconPerks_deadMansSwitch.png", "The Deathslinger"],
    ["Deadlock", "d/d3/IconPerks_deadlock.png", "The Cenobite"],
    ["Deathbound", "e/e7/IconPerks_deathbound.png", "The Executioner"],
    ["Deerstalker", "0/01/IconPerks_deerstalker.png", ""],
    ["Discordance", "8/82/IconPerks_discordance.png", "The Legion"],
    ["Dissolution", "1/1d/IconPerks_dissolution.png", "The Dredge"],
    ["Distressing", "9/94/IconPerks_distressing.png", ""],
    ["Dragon's Grip", "f/ff/IconPerks_dragonsGrip.png", "The Blight"],
    ["Dying Light", "4/48/IconPerks_dyingLight.png", "The Shape"],
    ["Enduring", "9/94/IconPerks_enduring.png", "The Hillbilly"],
    ["Eruption", "d/dd/IconPerks_eruption.png", "The Nemesis"],
    ["Fearmonger", "0/0f/IconPerks_mindbreaker.png", ""],
    ["Fire Up", "5/5c/IconPerks_fireUp.png", "The Nightmare"],
    ["Forced Penance", "1/1d/IconPerks_forcedPenance.png", "The Executioner"],
    ["Franklin's Demise", "b/b2/IconPerks_franklinsDemise.png", "The Cannibal"],
    ["Furtive Chase", "9/94/IconPerks_furtiveChase.png", "The Ghost Face"],
    ["Gearhead", "f/fd/IconPerks_gearhead.png", "The Deathslinger"],
    ["Grim Embrace", "1/1c/IconPerks_grimEmbrace.png", "The Artist"],
    ["Hangman's Trick", "b/b4/IconPerks_hangmansTrick.png", "The Pig"],
    ["Hex: Blood Favour", "6/6b/IconPerks_hexBloodFavour.png", "The Blight"],
    ["Hex: Crowd Control", "f/f1/IconPerks_hexCrowdControl.png", "The Trickster"],
    ["Hex: Devour Hope", "c/c9/IconPerks_hexDevourHope.png", "The Hag"],
    ["Hex: Face the Darkness", "a/af/IconPerks_hexFaceTheDarkness.png", "The Knight"],
    ["Hex: Haunted Ground", "c/c4/IconPerks_hexHauntedGround.png", "The Spirit"],
    ["Hex: Huntress Lullaby", "1/11/IconPerks_hexHuntressLullaby.png", "The Huntress"],
    ["Hex: No One Escapes Death", "a/af/IconPerks_hexNoOneEscapesDeath.png", ""],
    ["Hex: Pentimento", "5/5d/IconPerks_hexPentimento.png", "The Artist"],
    ["Hex: Plaything", "1/18/IconPerks_hexPlaything.png", "The Cenobite"],
    ["Hex: Retribution", "a/ab/IconPerks_hexRetribution.png", "The Deathslinger"],
    ["Hex: Ruin", "a/a2/IconPerks_hexRuin.png", "The Hag"],
    ["Hex: The Third Seal", "3/36/IconPerks_hexTheThirdSeal.png", "The Hag"],
    ["Hex: Thrill of the Hunt", "0/02/IconPerks_hexThrillOfTheHunt.png", ""],
    ["Hex: Undying", "f/fe/IconPerks_hexUndying.png", "The Blight"],
    ["Hoarder", "2/23/IconPerks_hoarder.png", "The Twins"],
    ["Hubris", "a/aa/IconPerks_hubris.png", "The Knight"],
    ["Hysteria", "3/3a/IconPerks_hysteria.png", "The Nemesis"],
    ["I'm All Ears", "e/e3/IconPerks_imAllEars.png", "The Ghost Face"],
    ["Infectious Fright", "6/6d/IconPerks_infectiousFright.png", "The Plague"],
    ["Insidious", "4/40/IconPerks_insidious.png", ""],
    ["Iron Grasp", "1/14/IconPerks_ironGrasp.png", ""],
    ["Iron Maiden", "b/b0/IconPerks_ironMaiden.png", "The Legion"],
    ["Jolt", "3/3b/IconPerks_surge.png", ""],
    ["Knock Out", "5/52/IconPerks_knockOut.png", "The Cannibal"],
    ["Lethal Pursuer", "6/61/IconPerks_lethalPursuer.png", "The Nemesis"],
    ["Lightborn", "4/48/IconPerks_lightborn.png", "The Hillbilly"],
    ["Mad Grit", "d/da/IconPerks_madGrit.png", "The Legion"],
    ["Make Your Choice", "6/6b/IconPerks_makeYourChoice.png", "The Pig"],
    ["Merciless Storm", "3/36/IconPerks_mercilessStorm.png/revision/latest?cb=20220216120012", "The Onryō"],
    ["Monitor & Abuse", "6/60/IconPerks_monitorAndAbuse.png", "The Doctor"],
    ["Nemesis", "3/33/IconPerks_nemesis.png", "The Oni"],
    ["No Way Out", "b/bb/IconPerks_noWayOut.png", "The Trickster"],
    ["Nowhere to Hide", "2/29/IconPerks_nowhereToHide.png", "The Knight"],
    ["Oppression", "a/a1/IconPerks_oppression.png", "The Twins"],
    ["Overcharge", "c/c3/IconPerks_overcharge.png", "The Doctor"],
    ["Overwhelming Presence", "9/9a/IconPerks_overwhelmingPresence.png", "The Doctor"],
    ["Play with Your Food", "1/18/IconPerks_playWithYourFood.png", "The Shape"],
    ["Pop Goes the Weasel", "0/0f/IconPerks_popGoesTheWeasel.png", "The Clown"],
    ["Predator", "7/73/IconPerks_predator.png", "The Wraith"],
    ["Rancor", "a/a2/IconPerks_rancor.png", "The Spirit"],
    ["Remember Me", "6/62/IconPerks_rememberMe.png", "The Nightmare"],
    ["Save The Best for Last", "6/6a/IconPerks_saveTheBestForLast.png", "The Shape"],
    ["Scourge Hook: Floods of Rage", "1/1c/IconPerks_scourgeHookFloodsOfRage.png", "The Onryō"],
    ["Scourge Hook: Gift of Pain", "2/26/IconPerks_scourgeHookGiftOfPain.png", "The Cenobite"],
    ["Scourge Hook: Monstrous Shrine", "f/f5/IconPerks_monstrousShrine.png", ""],
    ["Scourge Hook: Pain Resonance", "7/79/IconPerks_scourgeHookPainResonance.png", "The Artist"],
    ["Septic Touch", "d/d8/IconPerks_septicTouch.png", "The Dredge"],
    ["Shadowborn", "a/ac/IconPerks_shadowborn.png", "The Wraith"],
    ["Shattered Hope", "a/aa/IconPerks_shatteredHope.png", ""],
    ["Sloppy Butcher", "5/5a/IconPerks_sloppyButcher.png", ""],
    ["Spies from the Shadows", "b/b1/IconPerks_spiesFromTheShadows.png", ""],
    ["Spirit Fury", "a/a6/IconPerks_spiritFury.png", "The Spirit"],
    ["Starstruck", "6/6e/IconPerks_starstruck.png", "The Trickster"],
    ["Stridor", "3/32/IconPerks_stridor.png", "The Nurse"],
    ["Superior Anatomy", "a/aa/IconPerks_superiorAnatomy.png", "The Mastermind"],
    ["Surveillance", "e/eb/IconPerks_surveillance.png", "The Pig"],
    ["Terminus", "4/4c/IconPerks_terminus.png", "The Mastermind"],
    ["Territorial Imperative", "2/2a/IconPerks_territorialImperative.png", "The Huntress"],
    ["Thanatophobia", "a/a2/IconPerks_thanatophobia.png", "The Nurse"],
    ["Thrilling Tremors", "b/b8/IconPerks_thrillingTremors.png", "The Ghost Face"],
    ["Tinkerer", "d/d9/IconPerks_tinkerer.png", "The Hillbilly"],
    ["Trail of Torment", "9/94/IconPerks_trailOfTorment.png", "The Executioner"],
    ["Unnerving Presence", "a/a4/IconPerks_unnervingPresence.png", "The Trapper"],
    ["Unrelenting", "5/57/IconPerks_unrelenting.png", ""],
    ["Whispers", "b/bb/IconPerks_whispers.png", ""],
    ["Zanshin Tactics", "d/d3/IconPerks_zanshinTactics.png", "The Oni"],
];

export const DBD_PERKS = {
    survivor: SURVIVOR.map(toPerk('survivor')),
    killer: KILLER.map(toPerk('killer')),
};
